spring.application.name=GMUP
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/gmup
spring.datasource.username=postgres
spring.datasource.password=55455
server.port=8081


minio.endpoint=http://localhost:9000
minio.access-key=admin
minio.secret-key=admin123
minio.bucket-name=my-project-files


spring.servlet.multipart.max-file-size=1000MB


spring.servlet.multipart.max-request-size=1000MB